import type { ATSPlatform } from "@/lib/ats/registry"
import type { CompanyType } from "@/lib/companies/types"

export interface SeedCompany {
  name: string
  /** null = not confidently classifiable → no tag shown (plan Task 2.5). */
  companyType: CompanyType | null
  /** The company's own public job board, when one was verified. */
  board: { platform: ATSPlatform; token: string } | null
}

const gh = (token: string) => ({ platform: "greenhouse" as const, token })
const lever = (token: string) => ({ platform: "lever" as const, token })

/**
 * Curated companies (plan Task 2.5), seeded into `companies` by
 * supabase/migrations/20260916000000_companies_board_tokens_and_seed.sql —
 * seed-data.test.ts fails if the two drift apart. Change a company: edit
 * here, then add a NEW migration (never edit an applied one).
 *
 * Boards were verified live on 2026-09-15 against the public job-board
 * APIs. A token was kept only when the board's own company name matched
 * and it had at least one open job. That second rule matters: Workable
 * answers 200 for any registered account name, and every Workable hit
 * (e.g. "apple", "meta") had zero jobs — none were kept. Name matches that
 * turned out to be other organisations were rejected by hand (Lever "neon"
 * is a Brazilian bank, "linkedin" a partner sandbox; Greenhouse "remote"
 * is General Assembly, "binance" a template board, "warp" ambiguous).
 *
 * company_type uses the size bands in lib/companies/types.ts, from public
 * headcount figures. Companies within ~15% of a band edge, or growing fast
 * enough to cross one soon, are left null rather than guessed.
 */
export const SEED_COMPANIES: SeedCompany[] = [
  { name: "Amazon", companyType: "faang-tier", board: null },
  { name: "Apple", companyType: "faang-tier", board: null },
  { name: "Google", companyType: "faang-tier", board: null },
  { name: "Meta", companyType: "faang-tier", board: null },
  { name: "Microsoft", companyType: "faang-tier", board: null },
  { name: "Netflix", companyType: "faang-tier", board: null },
  { name: "Adobe", companyType: "enterprise", board: null },
  { name: "Airbnb", companyType: "enterprise", board: gh("airbnb") },
  { name: "AMD", companyType: "enterprise", board: null },
  { name: "Atlassian", companyType: "enterprise", board: null },
  { name: "Autodesk", companyType: "enterprise", board: null },
  { name: "Block", companyType: "enterprise", board: gh("block") },
  { name: "Bloomberg", companyType: "enterprise", board: null },
  { name: "Booking.com", companyType: "enterprise", board: null },
  { name: "Cisco", companyType: "enterprise", board: null },
  { name: "CrowdStrike", companyType: "enterprise", board: null },
  { name: "Databricks", companyType: "enterprise", board: gh("databricks") },
  { name: "Datadog", companyType: "enterprise", board: gh("datadog") },
  { name: "DocuSign", companyType: "enterprise", board: null },
  { name: "DoorDash", companyType: "enterprise", board: gh("doordashusa") },
  { name: "eBay", companyType: "enterprise", board: null },
  { name: "Electronic Arts", companyType: "enterprise", board: null },
  { name: "Expedia Group", companyType: "enterprise", board: null },
  { name: "Goldman Sachs", companyType: "enterprise", board: null },
  { name: "HubSpot", companyType: "enterprise", board: gh("hubspotjobs") },
  { name: "IBM", companyType: "enterprise", board: null },
  { name: "Intel", companyType: "enterprise", board: null },
  { name: "Intuit", companyType: "enterprise", board: null },
  { name: "JPMorgan Chase", companyType: "enterprise", board: null },
  { name: "LinkedIn", companyType: "enterprise", board: null },
  { name: "Lucid Motors", companyType: "enterprise", board: gh("lucidmotors") },
  { name: "MongoDB", companyType: "enterprise", board: gh("mongodb") },
  { name: "Morgan Stanley", companyType: "enterprise", board: null },
  { name: "NVIDIA", companyType: "enterprise", board: null },
  { name: "Okta", companyType: "enterprise", board: gh("okta") },
  { name: "Oracle", companyType: "enterprise", board: null },
  { name: "Palo Alto Networks", companyType: "enterprise", board: null },
  { name: "PayPal", companyType: "enterprise", board: null },
  { name: "Qualcomm", companyType: "enterprise", board: null },
  { name: "Salesforce", companyType: "enterprise", board: null },
  { name: "SAP", companyType: "enterprise", board: null },
  { name: "ServiceNow", companyType: "enterprise", board: null },
  { name: "Shopify", companyType: "enterprise", board: null },
  { name: "Snap", companyType: "enterprise", board: null },
  { name: "Snowflake", companyType: "enterprise", board: null },
  { name: "SpaceX", companyType: "enterprise", board: gh("spacex") },
  { name: "Spotify", companyType: "enterprise", board: lever("spotify") },
  { name: "Stripe", companyType: "enterprise", board: gh("stripe") },
  { name: "Tesla", companyType: "enterprise", board: null },
  { name: "Toast", companyType: "enterprise", board: gh("toast") },
  { name: "Twilio", companyType: "enterprise", board: gh("twilio") },
  { name: "Uber", companyType: "enterprise", board: null },
  { name: "Wayfair", companyType: "enterprise", board: null },
  { name: "Workday", companyType: "enterprise", board: null },
  { name: "Zillow", companyType: "enterprise", board: null },
  { name: "Zoom", companyType: "enterprise", board: null },
  { name: "Zscaler", companyType: "enterprise", board: gh("zscaler") },
  { name: "Affirm", companyType: "mid-size", board: gh("affirm") },
  { name: "Airtable", companyType: "mid-size", board: gh("airtable") },
  { name: "Amplitude", companyType: "mid-size", board: gh("amplitude") },
  { name: "Arctic Wolf", companyType: "mid-size", board: null },
  { name: "Asana", companyType: "mid-size", board: gh("asana") },
  { name: "Attentive", companyType: "mid-size", board: gh("attentive") },
  { name: "Aurora", companyType: "mid-size", board: null },
  { name: "Benchling", companyType: "mid-size", board: null },
  { name: "Box", companyType: "mid-size", board: gh("boxinc") },
  { name: "Braze", companyType: "mid-size", board: gh("braze") },
  { name: "Brex", companyType: "mid-size", board: gh("brex") },
  { name: "Carta", companyType: "mid-size", board: gh("carta") },
  { name: "Chime", companyType: "mid-size", board: gh("chime") },
  { name: "Circle", companyType: "mid-size", board: null },
  { name: "ClickUp", companyType: "mid-size", board: null },
  { name: "Coinbase", companyType: "mid-size", board: gh("coinbase") },
  { name: "Confluent", companyType: "mid-size", board: null },
  { name: "Cribl", companyType: "mid-size", board: gh("cribl") },
  { name: "Dataiku", companyType: "mid-size", board: gh("dataiku") },
  { name: "DigitalOcean", companyType: "mid-size", board: gh("digitalocean98") },
  { name: "Discord", companyType: "mid-size", board: gh("discord") },
  { name: "Dropbox", companyType: "mid-size", board: gh("dropbox") },
  { name: "DRW", companyType: "mid-size", board: gh("drweng") },
  { name: "Duolingo", companyType: "mid-size", board: gh("duolingo") },
  { name: "Elastic", companyType: "mid-size", board: gh("elastic") },
  { name: "Etsy", companyType: "mid-size", board: null },
  { name: "Eventbrite", companyType: "mid-size", board: null },
  { name: "Faire", companyType: "mid-size", board: gh("faire") },
  { name: "Fastly", companyType: "mid-size", board: gh("fastly") },
  { name: "Figma", companyType: "mid-size", board: gh("figma") },
  { name: "Fivetran", companyType: "mid-size", board: gh("fivetran") },
  { name: "Flatiron Health", companyType: "mid-size", board: gh("flatironhealth") },
  { name: "Flexport", companyType: "mid-size", board: gh("flexport") },
  { name: "GitLab", companyType: "mid-size", board: gh("gitlab") },
  { name: "Glean", companyType: "mid-size", board: gh("gleanwork") },
  { name: "Gong", companyType: "mid-size", board: gh("gongio") },
  { name: "Grafana Labs", companyType: "mid-size", board: gh("grafanalabs") },
  { name: "Grammarly", companyType: "mid-size", board: null },
  { name: "Gusto", companyType: "mid-size", board: gh("gusto") },
  { name: "HashiCorp", companyType: "mid-size", board: null },
  { name: "Hudson River Trading", companyType: "mid-size", board: gh("wehrtyou") },
  { name: "IMC Trading", companyType: "mid-size", board: gh("imc") },
  { name: "Instacart", companyType: "mid-size", board: gh("instacart") },
  { name: "Intercom", companyType: "mid-size", board: null },
  { name: "Jane Street", companyType: "mid-size", board: gh("janestreet") },
  { name: "Jump Trading", companyType: "mid-size", board: gh("jumptrading") },
  { name: "Justworks", companyType: "mid-size", board: gh("justworks") },
  { name: "Klaviyo", companyType: "mid-size", board: gh("klaviyo") },
  { name: "Lyft", companyType: "mid-size", board: gh("lyft") },
  { name: "Lyra Health", companyType: "mid-size", board: lever("lyrahealth") },
  { name: "Marqeta", companyType: "mid-size", board: null },
  { name: "Mercury", companyType: "mid-size", board: gh("mercury") },
  { name: "Miro", companyType: "mid-size", board: null },
  { name: "Monzo", companyType: "mid-size", board: gh("monzo") },
  { name: "N26", companyType: "mid-size", board: gh("n26") },
  { name: "Netskope", companyType: "mid-size", board: gh("netskope") },
  { name: "New Relic", companyType: "mid-size", board: gh("newrelic") },
  { name: "Notion", companyType: "mid-size", board: null },
  { name: "Nuro", companyType: "mid-size", board: gh("nuro") },
  { name: "Opendoor", companyType: "mid-size", board: null },
  { name: "Optiver", companyType: "mid-size", board: gh("optiverus") },
  { name: "Oscar Health", companyType: "mid-size", board: gh("oscar") },
  { name: "Outreach", companyType: "mid-size", board: lever("outreach") },
  { name: "PagerDuty", companyType: "mid-size", board: gh("pagerduty") },
  { name: "Peloton", companyType: "mid-size", board: gh("peloton") },
  { name: "Plaid", companyType: "mid-size", board: null },
  { name: "Point72", companyType: "mid-size", board: gh("point72") },
  { name: "Postman", companyType: "mid-size", board: gh("postman") },
  { name: "Ramp", companyType: "mid-size", board: null },
  { name: "Reddit", companyType: "mid-size", board: gh("reddit") },
  { name: "Relativity Space", companyType: "mid-size", board: gh("relativity") },
  { name: "Remote", companyType: "mid-size", board: gh("remotecom") },
  { name: "Ripple", companyType: "mid-size", board: gh("ripple") },
  { name: "Robinhood", companyType: "mid-size", board: gh("robinhood") },
  { name: "Roblox", companyType: "mid-size", board: gh("roblox") },
  { name: "Rocket Lab", companyType: "mid-size", board: gh("rocketlab") },
  { name: "Rubrik", companyType: "mid-size", board: gh("rubrik") },
  { name: "Samsara", companyType: "mid-size", board: gh("samsara") },
  { name: "Scale AI", companyType: "mid-size", board: gh("scaleai") },
  { name: "SentinelOne", companyType: "mid-size", board: gh("sentinellabs") },
  { name: "Shield AI", companyType: "mid-size", board: lever("shieldai") },
  { name: "Smartsheet", companyType: "mid-size", board: gh("smartsheet") },
  { name: "Snyk", companyType: "mid-size", board: null },
  { name: "Spring Health", companyType: "mid-size", board: gh("springhealth66") },
  { name: "Squarepoint Capital", companyType: "mid-size", board: gh("squarepointcapital") },
  { name: "Squarespace", companyType: "mid-size", board: gh("squarespace") },
  { name: "Thumbtack", companyType: "mid-size", board: null },
  { name: "Tower Research Capital", companyType: "mid-size", board: gh("towerresearchcapital") },
  { name: "Twitch", companyType: "mid-size", board: gh("twitch") },
  { name: "Vercel", companyType: "mid-size", board: gh("vercel") },
  { name: "Verkada", companyType: "mid-size", board: gh("verkada") },
  { name: "Vimeo", companyType: "mid-size", board: null },
  { name: "Warby Parker", companyType: "mid-size", board: null },
  { name: "Waymo", companyType: "mid-size", board: gh("waymo") },
  { name: "Webflow", companyType: "mid-size", board: gh("webflow") },
  { name: "Zapier", companyType: "mid-size", board: null },
  { name: "Zocdoc", companyType: "mid-size", board: gh("zocdoc") },
  { name: "Zoox", companyType: "mid-size", board: lever("zoox") },
  { name: "Clerk", companyType: "startup", board: null },
  { name: "Descript", companyType: "startup", board: gh("descript") },
  { name: "Fly.io", companyType: "startup", board: null },
  { name: "Hex", companyType: "startup", board: gh("hextechnologies") },
  { name: "Imgur", companyType: "startup", board: null },
  { name: "Kickstarter", companyType: "startup", board: gh("kickstarter") },
  { name: "Medium", companyType: "startup", board: null },
  { name: "Modal", companyType: "startup", board: null },
  { name: "Mux", companyType: "startup", board: null },
  { name: "Netlify", companyType: "startup", board: gh("netlify") },
  { name: "Pitch", companyType: "startup", board: null },
  { name: "PlanetScale", companyType: "startup", board: gh("planetscale") },
  { name: "PostHog", companyType: "startup", board: null },
  { name: "Railway", companyType: "startup", board: null },
  { name: "Render", companyType: "startup", board: null },
  { name: "Sourcegraph", companyType: "startup", board: gh("sourcegraph91") },
  { name: "Substack", companyType: "startup", board: null },
  { name: "Tailscale", companyType: "startup", board: gh("tailscale") },
  { name: "Temporal", companyType: "startup", board: null },
  { name: "Anduril", companyType: null, board: gh("andurilindustries") },
  { name: "Anthropic", companyType: null, board: gh("anthropic") },
  { name: "Axon", companyType: null, board: gh("axon") },
  { name: "Betterment", companyType: null, board: gh("betterment") },
  { name: "Binance", companyType: null, board: lever("binance") },
  { name: "Calendly", companyType: null, board: gh("calendly") },
  { name: "Cloudflare", companyType: null, board: gh("cloudflare") },
  { name: "Cockroach Labs", companyType: null, board: gh("cockroachlabs") },
  { name: "Crypto.com", companyType: null, board: lever("crypto") },
  { name: "Epic Games", companyType: null, board: gh("epicgames") },
  { name: "Gemini", companyType: null, board: gh("gemini") },
  { name: "Instabase", companyType: null, board: gh("instabase") },
  { name: "Lattice", companyType: null, board: gh("lattice") },
  { name: "LaunchDarkly", companyType: null, board: gh("launchdarkly") },
  { name: "Mercari", companyType: null, board: gh("mercari") },
  { name: "Mixpanel", companyType: null, board: gh("mixpanel") },
  { name: "Nextdoor", companyType: null, board: gh("nextdoor") },
  { name: "Palantir", companyType: null, board: lever("palantir") },
  { name: "Pinterest", companyType: null, board: gh("pinterest") },
  { name: "Rigetti Computing", companyType: null, board: lever("rigetti") },
  { name: "Riot Games", companyType: null, board: gh("riotgames") },
  { name: "Ro", companyType: null, board: lever("ro") },
  { name: "Rover", companyType: null, board: lever("rover") },
  { name: "SeatGeek", companyType: null, board: gh("seatgeek") },
  { name: "SoFi", companyType: null, board: gh("sofi") },
  { name: "Toptal", companyType: null, board: lever("toptal") },
]
