-- Task 2.5 — Company Metadata Table: board tokens + seed data.
--
-- 1. Adds ats_platform/board_token to companies (documented deviation from
--    the plan's column list, same reasoning as jobs.board_token): discovery
--    (Task 2.2) needs "company name → board" for its curated-list-first
--    lookup, and ingestion needs "board → company" to give jobs a real name
--    and a company_id for the size/tier tag.
-- 2. Seeds the curated list. Source of truth: lib/companies/seed-data.ts;
--    lib/companies/seed-data.test.ts fails if the two drift apart.
--
-- Idempotent: safe to run more than once. Re-running updates seeded rows to
-- these values but never touches rows whose source is 'enriched'.

alter table public.companies add column if not exists ats_platform text;
alter table public.companies add column if not exists board_token text;

alter table public.companies drop constraint if exists companies_ats_platform_check;
alter table public.companies add constraint companies_ats_platform_check
  check (ats_platform is null or ats_platform in ('greenhouse', 'lever', 'workable'));

-- A board is both halves or neither.
alter table public.companies drop constraint if exists companies_board_pair_check;
alter table public.companies add constraint companies_board_pair_check
  check ((ats_platform is null) = (board_token is null));

-- Tokens are stored lowercase; one company per board.
alter table public.companies drop constraint if exists companies_board_token_lowercase_check;
alter table public.companies add constraint companies_board_token_lowercase_check
  check (board_token is null or board_token = lower(board_token));

create unique index if not exists companies_board_idx
  on public.companies (ats_platform, board_token)
  where board_token is not null;

-- Seed. Boards verified live on 2026-09-15: the board's own company name
-- matched and it had at least one open job (see seed-data.ts for method).
insert into public.companies (name, company_type, ats_platform, board_token, source)
values
  ('Amazon', 'faang-tier', null, null, 'manual'),
  ('Apple', 'faang-tier', null, null, 'manual'),
  ('Google', 'faang-tier', null, null, 'manual'),
  ('Meta', 'faang-tier', null, null, 'manual'),
  ('Microsoft', 'faang-tier', null, null, 'manual'),
  ('Netflix', 'faang-tier', null, null, 'manual'),
  ('Adobe', 'enterprise', null, null, 'manual'),
  ('Airbnb', 'enterprise', 'greenhouse', 'airbnb', 'manual'),
  ('AMD', 'enterprise', null, null, 'manual'),
  ('Atlassian', 'enterprise', null, null, 'manual'),
  ('Autodesk', 'enterprise', null, null, 'manual'),
  ('Block', 'enterprise', 'greenhouse', 'block', 'manual'),
  ('Bloomberg', 'enterprise', null, null, 'manual'),
  ('Booking.com', 'enterprise', null, null, 'manual'),
  ('Cisco', 'enterprise', null, null, 'manual'),
  ('CrowdStrike', 'enterprise', null, null, 'manual'),
  ('Databricks', 'enterprise', 'greenhouse', 'databricks', 'manual'),
  ('Datadog', 'enterprise', 'greenhouse', 'datadog', 'manual'),
  ('DocuSign', 'enterprise', null, null, 'manual'),
  ('DoorDash', 'enterprise', 'greenhouse', 'doordashusa', 'manual'),
  ('eBay', 'enterprise', null, null, 'manual'),
  ('Electronic Arts', 'enterprise', null, null, 'manual'),
  ('Expedia Group', 'enterprise', null, null, 'manual'),
  ('Goldman Sachs', 'enterprise', null, null, 'manual'),
  ('HubSpot', 'enterprise', 'greenhouse', 'hubspotjobs', 'manual'),
  ('IBM', 'enterprise', null, null, 'manual'),
  ('Intel', 'enterprise', null, null, 'manual'),
  ('Intuit', 'enterprise', null, null, 'manual'),
  ('JPMorgan Chase', 'enterprise', null, null, 'manual'),
  ('LinkedIn', 'enterprise', null, null, 'manual'),
  ('Lucid Motors', 'enterprise', 'greenhouse', 'lucidmotors', 'manual'),
  ('MongoDB', 'enterprise', 'greenhouse', 'mongodb', 'manual'),
  ('Morgan Stanley', 'enterprise', null, null, 'manual'),
  ('NVIDIA', 'enterprise', null, null, 'manual'),
  ('Okta', 'enterprise', 'greenhouse', 'okta', 'manual'),
  ('Oracle', 'enterprise', null, null, 'manual'),
  ('Palo Alto Networks', 'enterprise', null, null, 'manual'),
  ('PayPal', 'enterprise', null, null, 'manual'),
  ('Qualcomm', 'enterprise', null, null, 'manual'),
  ('Salesforce', 'enterprise', null, null, 'manual'),
  ('SAP', 'enterprise', null, null, 'manual'),
  ('ServiceNow', 'enterprise', null, null, 'manual'),
  ('Shopify', 'enterprise', null, null, 'manual'),
  ('Snap', 'enterprise', null, null, 'manual'),
  ('Snowflake', 'enterprise', null, null, 'manual'),
  ('SpaceX', 'enterprise', 'greenhouse', 'spacex', 'manual'),
  ('Spotify', 'enterprise', 'lever', 'spotify', 'manual'),
  ('Stripe', 'enterprise', 'greenhouse', 'stripe', 'manual'),
  ('Tesla', 'enterprise', null, null, 'manual'),
  ('Toast', 'enterprise', 'greenhouse', 'toast', 'manual'),
  ('Twilio', 'enterprise', 'greenhouse', 'twilio', 'manual'),
  ('Uber', 'enterprise', null, null, 'manual'),
  ('Wayfair', 'enterprise', null, null, 'manual'),
  ('Workday', 'enterprise', null, null, 'manual'),
  ('Zillow', 'enterprise', null, null, 'manual'),
  ('Zoom', 'enterprise', null, null, 'manual'),
  ('Zscaler', 'enterprise', 'greenhouse', 'zscaler', 'manual'),
  ('Affirm', 'mid-size', 'greenhouse', 'affirm', 'manual'),
  ('Airtable', 'mid-size', 'greenhouse', 'airtable', 'manual'),
  ('Amplitude', 'mid-size', 'greenhouse', 'amplitude', 'manual'),
  ('Arctic Wolf', 'mid-size', null, null, 'manual'),
  ('Asana', 'mid-size', 'greenhouse', 'asana', 'manual'),
  ('Attentive', 'mid-size', 'greenhouse', 'attentive', 'manual'),
  ('Aurora', 'mid-size', null, null, 'manual'),
  ('Benchling', 'mid-size', null, null, 'manual'),
  ('Box', 'mid-size', 'greenhouse', 'boxinc', 'manual'),
  ('Braze', 'mid-size', 'greenhouse', 'braze', 'manual'),
  ('Brex', 'mid-size', 'greenhouse', 'brex', 'manual'),
  ('Carta', 'mid-size', 'greenhouse', 'carta', 'manual'),
  ('Chime', 'mid-size', 'greenhouse', 'chime', 'manual'),
  ('Circle', 'mid-size', null, null, 'manual'),
  ('ClickUp', 'mid-size', null, null, 'manual'),
  ('Coinbase', 'mid-size', 'greenhouse', 'coinbase', 'manual'),
  ('Confluent', 'mid-size', null, null, 'manual'),
  ('Cribl', 'mid-size', 'greenhouse', 'cribl', 'manual'),
  ('Dataiku', 'mid-size', 'greenhouse', 'dataiku', 'manual'),
  ('DigitalOcean', 'mid-size', 'greenhouse', 'digitalocean98', 'manual'),
  ('Discord', 'mid-size', 'greenhouse', 'discord', 'manual'),
  ('Dropbox', 'mid-size', 'greenhouse', 'dropbox', 'manual'),
  ('DRW', 'mid-size', 'greenhouse', 'drweng', 'manual'),
  ('Duolingo', 'mid-size', 'greenhouse', 'duolingo', 'manual'),
  ('Elastic', 'mid-size', 'greenhouse', 'elastic', 'manual'),
  ('Etsy', 'mid-size', null, null, 'manual'),
  ('Eventbrite', 'mid-size', null, null, 'manual'),
  ('Faire', 'mid-size', 'greenhouse', 'faire', 'manual'),
  ('Fastly', 'mid-size', 'greenhouse', 'fastly', 'manual'),
  ('Figma', 'mid-size', 'greenhouse', 'figma', 'manual'),
  ('Fivetran', 'mid-size', 'greenhouse', 'fivetran', 'manual'),
  ('Flatiron Health', 'mid-size', 'greenhouse', 'flatironhealth', 'manual'),
  ('Flexport', 'mid-size', 'greenhouse', 'flexport', 'manual'),
  ('GitLab', 'mid-size', 'greenhouse', 'gitlab', 'manual'),
  ('Glean', 'mid-size', 'greenhouse', 'gleanwork', 'manual'),
  ('Gong', 'mid-size', 'greenhouse', 'gongio', 'manual'),
  ('Grafana Labs', 'mid-size', 'greenhouse', 'grafanalabs', 'manual'),
  ('Grammarly', 'mid-size', null, null, 'manual'),
  ('Gusto', 'mid-size', 'greenhouse', 'gusto', 'manual'),
  ('HashiCorp', 'mid-size', null, null, 'manual'),
  ('Hudson River Trading', 'mid-size', 'greenhouse', 'wehrtyou', 'manual'),
  ('IMC Trading', 'mid-size', 'greenhouse', 'imc', 'manual'),
  ('Instacart', 'mid-size', 'greenhouse', 'instacart', 'manual'),
  ('Intercom', 'mid-size', null, null, 'manual'),
  ('Jane Street', 'mid-size', 'greenhouse', 'janestreet', 'manual'),
  ('Jump Trading', 'mid-size', 'greenhouse', 'jumptrading', 'manual'),
  ('Justworks', 'mid-size', 'greenhouse', 'justworks', 'manual'),
  ('Klaviyo', 'mid-size', 'greenhouse', 'klaviyo', 'manual'),
  ('Lyft', 'mid-size', 'greenhouse', 'lyft', 'manual'),
  ('Lyra Health', 'mid-size', 'lever', 'lyrahealth', 'manual'),
  ('Marqeta', 'mid-size', null, null, 'manual'),
  ('Mercury', 'mid-size', 'greenhouse', 'mercury', 'manual'),
  ('Miro', 'mid-size', null, null, 'manual'),
  ('Monzo', 'mid-size', 'greenhouse', 'monzo', 'manual'),
  ('N26', 'mid-size', 'greenhouse', 'n26', 'manual'),
  ('Netskope', 'mid-size', 'greenhouse', 'netskope', 'manual'),
  ('New Relic', 'mid-size', 'greenhouse', 'newrelic', 'manual'),
  ('Notion', 'mid-size', null, null, 'manual'),
  ('Nuro', 'mid-size', 'greenhouse', 'nuro', 'manual'),
  ('Opendoor', 'mid-size', null, null, 'manual'),
  ('Optiver', 'mid-size', 'greenhouse', 'optiverus', 'manual'),
  ('Oscar Health', 'mid-size', 'greenhouse', 'oscar', 'manual'),
  ('Outreach', 'mid-size', 'lever', 'outreach', 'manual'),
  ('PagerDuty', 'mid-size', 'greenhouse', 'pagerduty', 'manual'),
  ('Peloton', 'mid-size', 'greenhouse', 'peloton', 'manual'),
  ('Plaid', 'mid-size', null, null, 'manual'),
  ('Point72', 'mid-size', 'greenhouse', 'point72', 'manual'),
  ('Postman', 'mid-size', 'greenhouse', 'postman', 'manual'),
  ('Ramp', 'mid-size', null, null, 'manual'),
  ('Reddit', 'mid-size', 'greenhouse', 'reddit', 'manual'),
  ('Relativity Space', 'mid-size', 'greenhouse', 'relativity', 'manual'),
  ('Remote', 'mid-size', 'greenhouse', 'remotecom', 'manual'),
  ('Ripple', 'mid-size', 'greenhouse', 'ripple', 'manual'),
  ('Robinhood', 'mid-size', 'greenhouse', 'robinhood', 'manual'),
  ('Roblox', 'mid-size', 'greenhouse', 'roblox', 'manual'),
  ('Rocket Lab', 'mid-size', 'greenhouse', 'rocketlab', 'manual'),
  ('Rubrik', 'mid-size', 'greenhouse', 'rubrik', 'manual'),
  ('Samsara', 'mid-size', 'greenhouse', 'samsara', 'manual'),
  ('Scale AI', 'mid-size', 'greenhouse', 'scaleai', 'manual'),
  ('SentinelOne', 'mid-size', 'greenhouse', 'sentinellabs', 'manual'),
  ('Shield AI', 'mid-size', 'lever', 'shieldai', 'manual'),
  ('Smartsheet', 'mid-size', 'greenhouse', 'smartsheet', 'manual'),
  ('Snyk', 'mid-size', null, null, 'manual'),
  ('Spring Health', 'mid-size', 'greenhouse', 'springhealth66', 'manual'),
  ('Squarepoint Capital', 'mid-size', 'greenhouse', 'squarepointcapital', 'manual'),
  ('Squarespace', 'mid-size', 'greenhouse', 'squarespace', 'manual'),
  ('Thumbtack', 'mid-size', null, null, 'manual'),
  ('Tower Research Capital', 'mid-size', 'greenhouse', 'towerresearchcapital', 'manual'),
  ('Twitch', 'mid-size', 'greenhouse', 'twitch', 'manual'),
  ('Vercel', 'mid-size', 'greenhouse', 'vercel', 'manual'),
  ('Verkada', 'mid-size', 'greenhouse', 'verkada', 'manual'),
  ('Vimeo', 'mid-size', null, null, 'manual'),
  ('Warby Parker', 'mid-size', null, null, 'manual'),
  ('Waymo', 'mid-size', 'greenhouse', 'waymo', 'manual'),
  ('Webflow', 'mid-size', 'greenhouse', 'webflow', 'manual'),
  ('Zapier', 'mid-size', null, null, 'manual'),
  ('Zocdoc', 'mid-size', 'greenhouse', 'zocdoc', 'manual'),
  ('Zoox', 'mid-size', 'lever', 'zoox', 'manual'),
  ('Clerk', 'startup', null, null, 'manual'),
  ('Descript', 'startup', 'greenhouse', 'descript', 'manual'),
  ('Fly.io', 'startup', null, null, 'manual'),
  ('Hex', 'startup', 'greenhouse', 'hextechnologies', 'manual'),
  ('Imgur', 'startup', null, null, 'manual'),
  ('Kickstarter', 'startup', 'greenhouse', 'kickstarter', 'manual'),
  ('Medium', 'startup', null, null, 'manual'),
  ('Modal', 'startup', null, null, 'manual'),
  ('Mux', 'startup', null, null, 'manual'),
  ('Netlify', 'startup', 'greenhouse', 'netlify', 'manual'),
  ('Pitch', 'startup', null, null, 'manual'),
  ('PlanetScale', 'startup', 'greenhouse', 'planetscale', 'manual'),
  ('PostHog', 'startup', null, null, 'manual'),
  ('Railway', 'startup', null, null, 'manual'),
  ('Render', 'startup', null, null, 'manual'),
  ('Sourcegraph', 'startup', 'greenhouse', 'sourcegraph91', 'manual'),
  ('Substack', 'startup', null, null, 'manual'),
  ('Tailscale', 'startup', 'greenhouse', 'tailscale', 'manual'),
  ('Temporal', 'startup', null, null, 'manual'),
  ('Anduril', null, 'greenhouse', 'andurilindustries', 'manual'),
  ('Anthropic', null, 'greenhouse', 'anthropic', 'manual'),
  ('Axon', null, 'greenhouse', 'axon', 'manual'),
  ('Betterment', null, 'greenhouse', 'betterment', 'manual'),
  ('Binance', null, 'lever', 'binance', 'manual'),
  ('Calendly', null, 'greenhouse', 'calendly', 'manual'),
  ('Cloudflare', null, 'greenhouse', 'cloudflare', 'manual'),
  ('Cockroach Labs', null, 'greenhouse', 'cockroachlabs', 'manual'),
  ('Crypto.com', null, 'lever', 'crypto', 'manual'),
  ('Epic Games', null, 'greenhouse', 'epicgames', 'manual'),
  ('Gemini', null, 'greenhouse', 'gemini', 'manual'),
  ('Instabase', null, 'greenhouse', 'instabase', 'manual'),
  ('Lattice', null, 'greenhouse', 'lattice', 'manual'),
  ('LaunchDarkly', null, 'greenhouse', 'launchdarkly', 'manual'),
  ('Mercari', null, 'greenhouse', 'mercari', 'manual'),
  ('Mixpanel', null, 'greenhouse', 'mixpanel', 'manual'),
  ('Nextdoor', null, 'greenhouse', 'nextdoor', 'manual'),
  ('Palantir', null, 'lever', 'palantir', 'manual'),
  ('Pinterest', null, 'greenhouse', 'pinterest', 'manual'),
  ('Rigetti Computing', null, 'lever', 'rigetti', 'manual'),
  ('Riot Games', null, 'greenhouse', 'riotgames', 'manual'),
  ('Ro', null, 'lever', 'ro', 'manual'),
  ('Rover', null, 'lever', 'rover', 'manual'),
  ('SeatGeek', null, 'greenhouse', 'seatgeek', 'manual'),
  ('SoFi', null, 'greenhouse', 'sofi', 'manual'),
  ('Toptal', null, 'lever', 'toptal', 'manual')
on conflict ((lower(name))) do update
  set company_type = excluded.company_type,
      ats_platform = excluded.ats_platform,
      board_token = excluded.board_token
  where public.companies.source = 'manual';
